product=input("Product Bought:")
quantity=int(input("How much do you need?"))
price=int(input("Enter how much it costs"))
bill=quantity*price
print("------------------")
print("Your invoice is")
print("1.Product:",product)
print("2.Quantity:",quantity)
print("3.Price:",price)
print("Your Bill is:",bill)
